<?php
/**
 * State-specific SEO Content Template
 * 
 * This file dynamically generates SEO-friendly content for specific states/provinces.
 * It uses the $rule array passed from CalculatorController and variables generated by SeoHelper.
 */

if (isset($isHome) && $isHome) return; // Do not show on home page

$stateName = htmlspecialchars($rule['state_name']);
$countrySlug = strtolower($rule['country_slug']);
$countryName = ucwords(str_replace('-', ' ', $countrySlug));
if ($countrySlug === 'usa') $countryName = 'USA';
?>

<div class="mt-16 max-w-3xl mx-auto text-slate-700 dark:text-slate-300 space-y-6 pb-12">

    <!-- ========================================== -->
    <!-- DISCLAIMER SECTION -->
    <!-- ========================================== -->
    <div class="mb-8 p-4 bg-amber-50 dark:bg-amber-900/30 border-l-4 border-amber-500 rounded-r-lg">
        <p class="text-sm text-amber-800 dark:text-amber-200">
            <strong>Disclaimer:</strong> This calculator provides an estimate for annual leave accrual and costs. It should not be used as a substitute for professional advice or detailed calculations as per your specific employment conditions or applicable laws in <?= $stateName ?>.
        </p>
    </div>

    <!-- ========================================== -->
    <!-- SEO ARTICLE SECTION -->
    <!-- ========================================== -->
    <div class="text-center mb-10">
        <h2 class="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">Annual Leave Calculator <?= $stateName ?> (<?= $countryName ?>)</h2>
    </div>

    <!-- Dynamic Spintax Introduction -->
    <?= $seoIntro ?? '' ?>

    <h2 class="text-2xl font-semibold text-slate-900 dark:text-white mt-12 mb-4">Understanding Annual Leave in <?= $stateName ?></h2>

    <p class="leading-relaxed">Under the applicable employment standards for <?= $countryName ?>, most full-time and part-time employees are entitled to paid annual leave for every year of service. Leave accumulates progressively throughout the year based on ordinary hours worked.</p>

    <p class="leading-relaxed">The amount of leave an employee earns depends on their employment arrangement:</p>
    <ul class="list-disc list-inside space-y-2 ml-4">
        <li>Full-time employees receive the full annual leave entitlement.</li>
        <li>Part-time employees accrue leave proportionate to their regular working hours.</li>
        <li>Casual employees generally do not receive paid annual leave as their hourly rate usually includes a casual loading.</li>
    </ul>

    <p class="leading-relaxed mt-4">Because leave builds up gradually, employees can monitor their balance throughout the year rather than waiting until the end of a 12-month period.</p>

    <h2 class="text-2xl font-semibold text-slate-900 dark:text-white mt-12 mb-4">How Annual Leave Accrues in <?= $stateName ?></h2>

    <p class="leading-relaxed">Annual leave accumulates continuously as employees work their ordinary hours. The standard entitlement is equivalent to <?= floatval($rule['annual_leave_weeks']) ?> weeks of paid leave each year.</p>

    <p class="leading-relaxed">For employees working a standard <?= floatval($rule['working_hours_per_week']) ?>-hour week, leave accrues at a consistent weekly rate.</p>

    <h3 class="text-xl font-medium text-slate-800 dark:text-slate-200 mt-6 mb-3">Annual Leave Accrual Formula</h3>

    <p class="leading-relaxed">To estimate annual leave accrual, use the following calculation:</p>

    <div class="bg-slate-100 dark:bg-slate-800 p-4 rounded-lg font-mono text-sm my-4 border border-slate-200 dark:border-slate-700">
        Annual Leave Accrued = (Weekly Ordinary Hours × <?= floatval($rule['annual_leave_weeks']) ?>) ÷ 52
    </div>

    <?php $weeklyHours = floatval($rule['working_hours_per_week']); $weeklyAccrual = round(($weeklyHours * floatval($rule['annual_leave_weeks'])) / 52, 3); ?>
    <p class="leading-relaxed">For an employee working <?= $weeklyHours ?> hours per week:</p>
    <p class="leading-relaxed font-mono font-medium bg-brand-50 dark:bg-brand-900/20 text-brand-700 dark:text-brand-300 inline-block px-2 py-1 rounded">(<?= $weeklyHours ?> × <?= floatval($rule['annual_leave_weeks']) ?>) ÷ 52 = <?= $weeklyAccrual ?> hours</p>

    <p class="leading-relaxed mt-2">This means a full-time employee accumulates approximately <?= $weeklyAccrual ?> hours of annual leave every week.</p>

    <!-- ========================================== -->
    <!-- FAQ SECTION -->
    <!-- ========================================== -->
    <div class="mt-16 bg-brand-50 dark:bg-slate-800 rounded-2xl p-8 border border-brand-100 dark:border-slate-700 shadow-sm">
        <h2 class="text-2xl font-bold text-slate-900 dark:text-white mb-6">Frequently Asked Questions</h2>
        
        <div class="space-y-6">
            <?php if (isset($faqs) && is_array($faqs)): ?>
                <?php foreach ($faqs as $faq): ?>
                <div class="faq-item">
                    <h3 class="font-bold text-slate-900 dark:text-white text-lg"><?= htmlspecialchars($faq['question']) ?></h3>
                    <p class="text-slate-700 dark:text-slate-300 mt-2 leading-relaxed"><?= htmlspecialchars($faq['answer']) ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>

    <!-- ========================================== -->
    <!-- CLOSING SECTION -->
    <!-- ========================================== -->
    <h2 class="text-2xl font-semibold text-slate-900 dark:text-white mt-12 mb-4">Calculate Your Leave With Confidence</h2>
    
    <!-- Dynamic Spintax Conclusion -->
    <?= $seoConclusion ?? '' ?>

</div>
